buildDrafts: false
buildFuture: false
buildExpored: false
buildExpired: false

params:
  env: production
  privacy:
    microsoftClarity:
      disable: true

privacy:
  googleAnalytics:
    disable: true
    